import { createCanvas, loadImage } from 'canvas';
import { writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const SRC  = path.join(root, 'assets', 'FELLA_CAT.png');
const OUT  = path.join(root, 'src', 'ui', 'components', 'cat-art.ts');

const TARGET_COLS = 28;
const TARGET_ROWS = 20;

const img    = await loadImage(SRC);
const canvas = createCanvas(TARGET_COLS, TARGET_ROWS * 2);
const ctx    = canvas.getContext('2d');
ctx.drawImage(img, 0, 0, TARGET_COLS, TARGET_ROWS * 2);
const { data } = ctx.getImageData(0, 0, TARGET_COLS, TARGET_ROWS * 2);

function px(x, y) {
  const i = (y * TARGET_COLS + x) * 4;
  return { r: data[i], g: data[i+1], b: data[i+2], a: data[i+3] };
}
function hex(r, g, b) {
  return '#' + [r, g, b].map(v => v.toString(16).padStart(2, '0')).join('');
}

// Cell types:
//   { t: 's' }                       — both transparent  space
//   { t: 'l'; fg: string }           — lower half block only (, no bg)
//   { t: 'u'; fg: string }           — upper half block only (, no bg)
//   { t: 'f'; fg: string; bg: string } — full block with both colors
const rows = [];
for (let row = 0; row < TARGET_ROWS; row++) {
  const cells = [];
  for (let col = 0; col < TARGET_COLS; col++) {
    const top = px(col, row * 2);
    const bot = px(col, row * 2 + 1);
    const topFilled = top.a >= 32;
    const botFilled = bot.a >= 32;
    if (!topFilled && !botFilled) {
      cells.push({ t: 's' });
    } else if (!topFilled) {
      cells.push({ t: 'l', fg: hex(bot.r, bot.g, bot.b) });
    } else if (!botFilled) {
      cells.push({ t: 'u', fg: hex(top.r, top.g, top.b) });
    } else {
      cells.push({ t: 'f', bg: hex(top.r, top.g, top.b), fg: hex(bot.r, bot.g, bot.b) });
    }
  }
  rows.push(cells);
}

const ts = `// AUTO-GENERATED by scripts/gen-cat-art.mjs -- do not edit manually.
export type CatCell =
  | { t: 's' }
  | { t: 'l'; fg: string }
  | { t: 'u'; fg: string }
  | { t: 'f'; fg: string; bg: string };
export const CAT_ART: CatCell[][] = ${JSON.stringify(rows, null, 2)};
`;

writeFileSync(OUT, ts, 'utf8');
console.log('Cat art written to ' + OUT + ' (' + TARGET_COLS + ' x ' + TARGET_ROWS + ')');
